from .constants import (
    MAX_FLIGHT_TIME_LOOKAHEAD,
    NUM_SENSORS,
    VALID_MIN_FLIGHT_TIME,
    VALID_MAX_FLIGHT_TIME,
    DROP_SENSORS_THRESHOLD,
    COSINE_SIMILARITY_THRESHOLD,
    SUM_THRESHOLD,
    HALF_WINDOW_SIZE,
    LOG_PATTERN,
    FLIGHT_TIME_PATTERN
)

# Data Loading Constants
DATA_LOADING = {
    'MAX_FLIGHT_TIME_LOOKAHEAD': MAX_FLIGHT_TIME_LOOKAHEAD
}

# You can also create groups of constants
DATA_PROCESSING = {
    'VALID_MIN_FLIGHT_TIME': VALID_MIN_FLIGHT_TIME,
    'VALID_MAX_FLIGHT_TIME': VALID_MAX_FLIGHT_TIME,
    'NUM_SENSORS': NUM_SENSORS,
    'DROP_SENSORS_THRESHOLD': DROP_SENSORS_THRESHOLD,
    'COSINE_SIMILARITY_THRESHOLD': COSINE_SIMILARITY_THRESHOLD,
    'SUM_THRESHOLD': SUM_THRESHOLD,
    'HALF_WINDOW_SIZE': HALF_WINDOW_SIZE
}

PATTERNS = {
    'LOG_PATTERN': LOG_PATTERN,
    'FLIGHT_TIME_PATTERN': FLIGHT_TIME_PATTERN
}
